[[client]]
id = 0
connected_drone_ids = [8]

[[client]]
id = 12
connected_drone_ids = [11]

[[server]]
id = 1
connected_drone_ids = [2, 3]

[[server]]
id = 13
connected_drone_ids = [2, 3]

[[server]]
id = 14
connected_drone_ids = [2, 3]

[[drone]]
id = 2
connected_node_ids = [1, 3, 4, 6, 13, 14]
pdr = 0.0

[[drone]]
id = 3
connected_node_ids = [1, 2, 5, 7, 13, 14]
pdr = 0.0

[[drone]]
id = 4
connected_node_ids = [2, 8, 9]
pdr = 0.0

[[drone]]
id = 5
connected_node_ids = [3, 8, 9]
pdr = 0.0

[[drone]]
id = 6
connected_node_ids = [2, 10, 11]
pdr = 0.0

[[drone]]
id = 7
connected_node_ids = [3, 10, 11]
pdr = 0.0

[[drone]]
id = 8
connected_node_ids = [0, 4, 5]
pdr = 0.0

[[drone]]
id = 9
connected_node_ids = [5, 4]
pdr = 0.0

[[drone]]
id = 10
connected_node_ids = [6, 7]
pdr = 0.0

[[drone]]
id = 11
connected_node_ids = [6, 7, 12]
pdr = 0.0

