[[client]]
id = 0
connected_drone_ids = [4]

[[client]]
id = 1
connected_drone_ids = [9]

[[server]]
id = 2
connected_drone_ids = [6, 12]

[[server]]
id = 3
connected_drone_ids = [11, 13]

[[drone]]
id = 4
connected_node_ids = [0, 6, 7]
pdr = 0.0

[[drone]]
id = 5
connected_node_ids = [6, 7]
pdr = 0.0

[[drone]]
id = 6
connected_node_ids = [2, 4, 5, 12]
pdr = 0.0

[[drone]]
id = 7
connected_node_ids = [4, 5, 13]
pdr = 0.0

[[drone]]
id = 8
connected_node_ids = [10, 11]
pdr = 0.0

[[drone]]
id = 9
connected_node_ids = [1, 10, 11]
pdr = 0.0

[[drone]]
id = 10
connected_node_ids = [8, 9, 12]
pdr = 0.0

[[drone]]
id = 11
connected_node_ids = [3, 8, 9, 13]
pdr = 0.0

[[drone]]
id = 12
connected_node_ids = [2, 6, 10, 13]
pdr = 0.0

[[drone]]
id = 13
connected_node_ids = [3, 7, 11, 12]
pdr = 0.0