[[drone]]
id = 3
connected_node_ids = [1, 2]
pdr = 0.05

[[drone]]
id = 4
connected_node_ids = [1, 2]
pdr = 0.03

[[client]]
id = 1
connected_drone_ids = [3, 4]

[[server]]
id = 2
connected_drone_ids = [3, 4]
