[[client]]
id = 0
connected_drone_ids = [3, 5]

[[server]]
id = 1
connected_drone_ids = [4, 6]

[[server]]
id = 2
connected_drone_ids = [4, 6]

[[drone]]
id = 3
connected_node_ids = [0, 4]
pdr = 0.0

[[drone]]
id = 4
connected_node_ids = [1, 2, 3]
pdr = 0.0

[[drone]]
id = 5
connected_node_ids = [0, 6]
pdr = 0.0

[[drone]]
id = 6
connected_node_ids = [1, 2, 5]
pdr = 0.0